-- MySQL Script generated by MySQL Workbench
-- Wed Jan 18 08:22:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ZSPMOVIE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ZSPMOVIE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ZSPMOVIE` DEFAULT CHARACTER SET utf8 ;
USE `ZSPMOVIE` ;

-- -----------------------------------------------------
-- Table `ZSPMOVIE`.`uzytkownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZSPMOVIE`.`uzytkownicy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Haslo` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Admin` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZSPMOVIE`.`filmy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZSPMOVIE`.`filmy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nazwa` VARCHAR(45) NULL,
  `Opis` VARCHAR(45) NULL,
  `Typ` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZSPMOVIE`.`uzytkownicy_has_filmy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZSPMOVIE`.`uzytkownicy_has_filmy` (
  `uzytkownicy_id` INT NOT NULL,
  `filmy_id` INT NOT NULL,
  PRIMARY KEY (`uzytkownicy_id`, `filmy_id`),
  CONSTRAINT `fk_uzytkownicy_has_filmy_uzytkownicy`
    FOREIGN KEY (`uzytkownicy_id`)
    REFERENCES `ZSPMOVIE`.`uzytkownicy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uzytkownicy_has_filmy_filmy1`
    FOREIGN KEY (`filmy_id`)
    REFERENCES `ZSPMOVIE`.`filmy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
